### ISSUE TITLE
Unloading a script doesn't remove its class loader

### ISSUE THREAD

**Issue by bluelhf** [Moderocky/ByteSkript#14]
## Issue Description

When unloading a script using `Skript#unloadScript(Script)`, one would expect all traces of said script including its code to be removed, such that a new script with the same name can be loaded without problems. Currently, this is not the case: the `loaders` field of the Skript instance is not updated when a script is unloaded.

### Reproducing the Issue
1. Load a script
2. Unload the script
3. Observe the loaders list in the Skript instance

### Effects
- Old scripts are never truly deleted until the Skript instance is garbage collected or the program is restarted
- Classes from scripts that have the same name as an older script from the same session will not be available — when requested, the older classes will be returned. This also means that as long as the same Skript instance is kept, scripts cannot be "reloaded"; doing so would simply cause both scripts' class loaders to exist simultaneously, and since the older script's class loader has a lower index in the loaders list, its classes are always preferred.

### Not so simple!
This problem would be easy to fix if each class loader in the loaders array represented one script file. If this was the case, one could simply iterate `loaders`, look for the class loader that matches the class loader of the main class of the script, and then remove said class loader from the script, done trivially with the built-in `removeIf(Predicate<T>)` method. Sadly, though, `loaders` class loaders do not necessarily have a one-to-one correspondence with script files — many methods in `Skript` explicitly load `PostCompileClass`es by calling `createLoader()` for each class, even when those classes come from the same script.

## Solution
To solve this issue properly (and thus avoid unnecessary calls to `createLoader()`, create a more strict correspondence between class loaders and scripts, and allow for hot-swapping (reloading) of scripts), two things must be done:
- In places where several calls to `Skript#loadClass(String, byte[])` are issued, one call to `createLoader()` and then multiple calls to `SkriptMirror#loadClass(String, byte[])` should be issued instead.
- In `Skript#unloadScript(Script)`, the class loader that represents the script being unloaded should be properly removed from the list of active class loaders.

**Comment by Moderocky** [comment]
You could make a contribution for this 🙂 

If not I'll look into it when I'm back from my holiday.
